### ISSUE TITLE
Support projects hosted in locations other than GitHub

### ISSUE THREAD

**Issue by jongeorge1** [endjin/Endjin.RecommendedPractices.NuGet#11]
Various properties across the files, specifically in:
- Endjin.Common.GitHub.props
- Endjin.Common.NuGet.props
- Endjin.RecommendedPractices.nuspec

assume that the project is being hosted in GitHub. When trying to use the package with a solution hosted elsewhere - e.g. Azure DevOps, various warnings are displayed.

**Comment by idg10** [comment]
Good point. Some possible options:

1. detect non-GitHub scenarios and automatically opt out of this behaviour in those cases
1. add a flag projects can set to opt out
1. make GitHub support opt-in
1. separate this into `Endjin.RecommendedPractices.NuGet.GitHub`

The thing with the first option is that I'm not actually sure how easy that would be to do.

**Comment by jongeorge1** [comment]
Yes. I think the biggest problem is with SourceLink - we're bringing the SourceLink library in by making it a dependency of the package, so we don't have any way of switching between different SourceLink implementations.

I think realistically we need to move the GitHub bits into Endjin.RecommendedPractices.NuGet.GitHub and then create an equivalent AzureDevOps version.
