### ISSUE TITLE
PackageIcon.png behaviour baffles people

### ISSUE THREAD

**Issue by idg10** [endjin/Endjin.RecommendedPractices.NuGet#16]
We need to provide better behaviour when the `PackageIcon.png` file is missing.

One option would be just to supply a default icon so that there's something there. Another would be to generate a message explaining the options (either to supply an icon file, or to configure the project not to build a NuGet package).

**Comment by mwadams** [comment]
I would supply an Icon so people know where to put it, but *also* to spit out a warning that you have the default icon.

**Comment by idg10** [comment]
I'm wondering how that would work in practice. We can generate a warning at the moment we detect the absence of the file and copy in a default one, but that's a one time event. This means that warning will pop up once then never be seen again. However, the problem persists.

If we're going to provide this warning, it seems like it'd be better to continue to provide the warning until such time as the problem has been dealt with. Here are some ways I can think of to do that:

1. don't supply a default icon - that way the condition will be easy to detect, and will persist until fixed
2. supply a default icon and then, on ever build, inspect the file to see if it's a copy of the default icon
3. supply a default icon and also generate a sort of sentinel file called something like `YOU_NEED_TO_PROVIDE_A_REAL_PACKAGE_ICON` containing instructions, and raise the warning until such time as the developer deletes that file.

Any other ideas?

**Comment by HowardvanRooijen** [comment]
Provide a sensible default. If they decide they want to customise, it should be simple for them to update their own icon.

**Comment by idg10** [comment]
So if I understand @HowardvanRooijen, you don't want the warning message that @mwadams suggests? Just generate a generic package icon, and since it'll be right there in their solution folder, it'll be obvious enough what to do if they want something non-generic?

**Comment by HowardvanRooijen** [comment]
Personally yes. The confusion yesterday was that in solution explorer, inside my csproj file I had a ❌PackageIcon.png, so I dropped the PackageIcon into the proj folder... the ❌ disappeared but the build failed because the Icon was actually expected to be in the solution root. So if you just add a default icon in the solution root, the first time experience is that everything will work, and if they want to customise the icon, they can just override it... but you have enabled everything to get the user to a successful first build.

**Comment by mwadams** [comment]
I'm happy not to have a one-time warning, just a default in the right place.
