### ISSUE TITLE
Change using location to outside/before namespace declaration

### ISSUE THREAD

**Issue by idg10** [endjin/Endjin.RecommendedPractices.NuGet#27]
The Azure SDK's change from using `Microsoft.Azure.*` to `Azure.*` has caused us problems because we tend to include `Azure` as a nested element of a namespace. For example, if you try to write this:

```cs
namespace Corvus.Storage.Azure.BlobStorage
{
    using Azure.Storage.Blobs;
```

you will get an error because C#'s namespace rules mean that `Azure` will resolve to `Corvus.Storage.Azure` for any code that is inside that namespace, or, as in this case, inside a namespace that is nested in `Corvus.Storage.Azure`. So it interprets this as a using directive for `Corvus.Storage.Azure.Storage.Blobs`, which doesn't exist, and is not what what we meant.

The only way to avoid this is to use this rather ugly construction:

```cs
namespace Corvus.Storage.Azure.BlobStorage
{
    using global::Azure.Storage.Blobs;
```

@idg10 has never liked putting `using` inside `namespace`, so he's probably biased...but the practice has long been a source of occasional friction, because it also tends to cause baffling error messages if you get something slightly wrong in a using directive. For example, because endjin's house style is to have the entire namespace structure reflected in the folder structure (instead of the more common practice of taking the project name as the root namespace, using folders only for namespaces nested within that), it's surprisingly easy to end up accidentally stating bits of your namespace twice, ending up with something like this:

```cs
namespace Corvus.Random.Corvus.Random.Stuff
{
```

You're less likely to do this if you adopt the `Endjin.RecommendedPractices` NuGet package from the start because that sets your `<RootNamespace>` to be empty, but without that, VS will include the project name and the folder path in newly added files, leading to problems of the kind seen above. If you then put using directives inside such a namespace declaration, the compiler becomes hopelessly confused, and produces error messages that give you no real clue as to what's actually going on. (This can be particularly baffling when the file that contains this sort of double namespace is generated—we've seen examples of this crop up in specflow-generated code, for example. You can't even see the source of the problem in that case—you just get some very confusing error messages.) Another case is if you end up with a namespace and a class name that are the same: if you've put your using directives inside a namespace directive, you can get errors that make it very hard to realise what the root cause of the problem is.

The change in the Azure .NET SDK is the final straw. Whereas the other problems can generally be avoided if we're careful how we name things, the use of `Azure` as a top-level namespace makes it impossible for us to use `Azure` anywhere within any nested namespace without causing problems if we put our using directives inside our namespace declarations. So for that reason, the balance has now shifted in favour of putting using directives ahead of namespace declarations.

(Note, the forthcoming file-scoped namespace declarations in C# 10 don't change much. The choice of putting your using directives inside or outside a namespace declaration turns into a choice between putting them after or before the namespace declaration.)

**Comment by mwadams** [comment]
I agree that the time has come to shift this.

Another reason I think are compelling - in-the-box tooling won't (or at least, I can't get it to) create files with the namespaces inside the using statement, regardless of the .editorConfig settings.

I would also add that the new "ambient" project-level usings will have a significant impact. The reason given for putting the namespaces where they are is ostensibly to make them less "noisy" at the top of the file. Now that it is possible to hide all the "usual suspects" with the ambient usings, they become a declaration of the "interesting" included scopes.

**Comment by idg10** [comment]
Ah, yes, good point. I forgot to mention global using directives. For anyone else ready this who might not have come across them yet, these are another feature coming in C# 10, distinct from the file-scoped namespace declarations I mentioned earlier. But the way to two features interact is relevant here.

Global using directives are never affected by namespace declarations. They can't be, because by definition they apply to all files in the project, and each file can contain zero or more different namespace declarations. So the only way for global using directives to have a consistent meaning is for them to act like the kind that are defined outside of a namespace declaration (or, if you're using the new C# 10 file-scoped declarations, global using directives act like the kind that appear before the namespace declaration).

This means that if you use global using directives at all, then you already have some using directives that are of the "outside/before the namespace declaration" kind, meaning that if you then go on to write any "inside/after the namespace declaration" kind in individual files, you've got a mixture of the two mechanisms in use. And while the behaviour for that is perfectly well-defined by the C# language spec, my view is that this is an extra source of inconsistency that we could well live without, and so it's another nail in the coffin for the "insider/after the namespace declaration" style.

**Comment by idg10** [comment]
Close by #36
